### ISSUE TITLE
push request

### ISSUE THREAD

**Issue by mbratukha** [ArtemZag/academy13#1]
Ребят, пожалуйста, перед тем, как пушите свои изменения (в master ветку) делайте pull либо fetch. Так же, когда начинаете работу над своим проектом (сели кодить), то так же рекомендуется делать pull, тогда меньше конфликтов будет вылазить. Если вы этого не будете делать, то такой файл как *.suo будет тянуться до бесконечности.

**Comment by Maaak** [comment]
Миша, я честно соблюдаю такой подход: сделал pull, открыл студию, нагадил, сделал коммит, сделал pull, сделал push. Но перед push обычно еще что-то рука мержу. ((

**Comment by mbratukha** [comment]
Ну судя из того, что *.suo всё же появляется изредка, то кто-то так не делает. Ибо в гитигноре он уже валяется, а появится мог только из-за того, что кто-то не сделал pull
