### ISSUE TITLE
Any problem with database

### ISSUE THREAD

**Issue by Maaak** [ArtemZag/academy13#4]
If somebody has problems with database:
1. remove database from project by removing it from SQL server object explorer
2. check if it not present on next path "academy13\BinaryStudio.PhotoGallery.Web\App_Data\BinaryStudio.PhotoGallery.Database.DatabaseContext.mdf". 
3. clear solution
4. rebuild solution
5. ... say me

**Comment by mbratukha** [comment]
I done step by step and then I got this error:
![image](https://f.cloud.github.com/assets/1413357/834495/861f67a0-f2c1-11e2-976a-7df67d9922d3.png)

File realy not exist

**Comment by Maaak** [comment]
Solved by https://github.com/ArtemZag/academy13/commit/514aed2d89fe2f04e67df8a73b78ba23db58438f
