### ISSUE TITLE
Deleting photo problem

### ISSUE THREAD

**Issue by AntonHolovin** [ArtemZag/academy13#6]
When we delete album, we forget name of it. But we need to know name of the album when PhotoCleaupTask starts working.. Because PhotoCleaupTask must to build path with album name and user name (where we must get UserModel from AlbumModel by foreign key). 

Who knows solution? Maybe we must to store path to original photo in PhotoModel?

**Comment by Maaak** [comment]
Solution: let's makr an album IsDeleted too. And only PhotoCleaupTask will delete it permanently...

**Comment by AntonHolovin** [comment]
But what about storing full path to photo in PhotoModel? It's exactly worse?

**Comment by Maaak** [comment]
There is no reason for it

**Comment by AntonHolovin** [comment]
oook
